apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  slack-token: https://hooks.slack.com/services/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
