apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd

data:
  service.slack: |
    token: $slack-token

  context: |
    argocdUrl: https://argocd.example.com

  template.app-sync-succeeded: |
    slack:
      attachments: |
        [{
          "color": "#18be52",
          "title": "{{ .app.metadata.name }} synced",
          "title_link": "{{ .context.argocdUrl }}/applications/{{ .app.metadata.name }}",
          "fields": [
            {
              "title": "Revision",
              "value": "{{ .app.status.sync.revision }}",
              "short": true
            },
            {
              "title": "Images",
              "value": "{{ range .app.status.summary.images }}• {{ . }}\\n{{ end }}",
              "short": false
            }
          ]
        }]

  trigger.on-sync-succeeded: |
    - description: Application synced successfully
      oncePer: app.status.sync.revision
      send:
        - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
