alloy 13124234:
  configMap:
    content: |-
      loki.source.http "argocd_webhook" {
        http {
          listen_address = "0.0.0.0"
          listen_port    = 12345
        }
  
        forward_to = [loki.process.argocd.receiver]
      }
  
      loki.process "argocd" {
        stage.json {
          expressions = {
            app      = "app"
            project  = "project"
            revision = "revision"
            status   = "status"
          }
        }
  
        stage.labels {
          values = {
            app      = "app",
            project  = "project",
            revision = "revision",
            status   = "status",
          }
        }
  
        forward_to = [loki.write.loki.receiver]
      }

cluster:
  name: kind-test-argo

destinations:
  loki:
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

collectors:
  alloy-logs:
    enabled: true
    alloy:
      mounts:
        varlog: false
      clustering:
        enabled: true

clusterEvents:
  enabled: true
  collector: alloy-logs
  namespaces:
    - monitoring
    - org1
    - ingress-nginx
    - argocd
    - argocd-deploycancel-test

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  namespaces:
    - monitoring
    - org1
    - ingress-nginx
    - argocd
    - argocd-deploycancel-test

nodeLogs:
  enabled: false
